-- ============================================================
-- DEV INTEL: BigQuery Historical Backfill
-- ============================================================
-- Source: githubarchive.day.* (public dataset)
-- Strategy: 
--   1. Upload repo list as temp table (repo_taxonomy)
--   2. Query GH Archive PushEvents matching those repos
--   3. Export results to GCS → download → load into Supabase
--
-- COST ESTIMATE:
--   GH Archive is ~2TB/year. Querying 2 years ≈ scanning 4TB.
--   BigQuery pricing: $6.25/TB = ~$25 total.
--   First 1TB/month is free, so first run might cost ~$19.
-- ============================================================

-- STEP 1: Create a temp table with your repo list
-- Upload the repo_list.csv (generated by seed_taxonomy.py) to a 
-- BigQuery dataset, e.g., dev_intel.repo_taxonomy
--
-- Schema: full_name STRING (e.g., "solana-labs/solana")
-- 
-- bq load --source_format=CSV dev_intel.repo_taxonomy repo_list.csv full_name:STRING

-- STEP 2: Pull all PushEvent commits for matching repos (last 2 years)
-- Run this query in BigQuery console or via bq CLI

CREATE TEMP FUNCTION extract_owner_repo(repo_name STRING) AS (
  LOWER(repo_name)
);

-- For a single month (adjust date range as needed):
SELECT
    c.sha                                          AS commit_sha,
    actor.login                                    AS github_username,
    actor.id                                       AS github_id,
    LOWER(repo.name)                               AS repo_full_name,
    TIMESTAMP(JSON_VALUE(c, '$.author.date'))       AS committed_at,
    SUBSTR(JSON_VALUE(c, '$.message'), 1, 500)      AS commit_message
FROM
    `githubarchive.month.2024*` AS events,        -- adjust: 2024*, 2025*, etc.
    UNNEST(JSON_QUERY_ARRAY(payload, '$.commits')) AS c
INNER JOIN
    `your_project.dev_intel.repo_taxonomy` AS tax  -- your uploaded repo list
ON
    LOWER(repo.name) = tax.full_name
WHERE
    type = 'PushEvent'
    AND actor.login IS NOT NULL
    AND actor.login NOT LIKE '%[bot]'              -- exclude bots
    AND actor.login NOT LIKE '%-bot'
    AND actor.login NOT LIKE '%Bot'
    AND actor.login != 'dependabot'
    AND actor.login != 'renovate'
    AND actor.login != 'github-actions'
    AND JSON_VALUE(c, '$.distinct') = 'true'       -- only count distinct commits

-- EXPECTED OUTPUT: ~5-20M rows for 2 years across top ecosystems
-- Export to GCS as newline-delimited JSON:
--   bq extract --destination_format=NEWLINE_DELIMITED_JSON \
--     'your_project:dev_intel.backfill_results' \
--     'gs://your-bucket/backfill/commits-*.json'

;

-- ============================================================
-- ALTERNATIVE: Smaller query for MVP (top 50 ecosystems only)
-- ============================================================
-- If you want a faster/cheaper first pass, filter to specific orgs:

SELECT
    c.sha                                          AS commit_sha,
    actor.login                                    AS github_username,
    actor.id                                       AS github_id,
    LOWER(repo.name)                               AS repo_full_name,
    TIMESTAMP(JSON_VALUE(c, '$.author.date'))       AS committed_at,
    SUBSTR(JSON_VALUE(c, '$.message'), 1, 500)      AS commit_message
FROM
    `githubarchive.month.202501` AS events,        -- single month for testing
    UNNEST(JSON_QUERY_ARRAY(payload, '$.commits')) AS c
WHERE
    type = 'PushEvent'
    AND actor.login IS NOT NULL
    AND actor.login NOT LIKE '%[bot]'
    AND JSON_VALUE(c, '$.distinct') = 'true'
    AND (
        -- Top ecosystem orgs (add more as needed)
        STARTS_WITH(LOWER(repo.name), 'ethereum/')
        OR STARTS_WITH(LOWER(repo.name), 'solana-labs/')
        OR STARTS_WITH(LOWER(repo.name), 'solana-foundation/')
        OR STARTS_WITH(LOWER(repo.name), 'ApeWorX/')
        OR STARTS_WITH(LOWER(repo.name), 'base-org/')
        OR STARTS_WITH(LOWER(repo.name), 'bnb-chain/')
        OR STARTS_WITH(LOWER(repo.name), 'MystenLabs/')
        OR STARTS_WITH(LOWER(repo.name), 'aptos-labs/')
        OR STARTS_WITH(LOWER(repo.name), 'near/')
        OR STARTS_WITH(LOWER(repo.name), 'cosmos/')
        OR STARTS_WITH(LOWER(repo.name), 'polkadot-fellows/')
        OR STARTS_WITH(LOWER(repo.name), 'arbitrum/')
        OR STARTS_WITH(LOWER(repo.name), 'Uniswap/')
        OR STARTS_WITH(LOWER(repo.name), 'aave/')
    )
;
